compiler-core:
  - changed-files:
    - any-glob-to-any-file:
      - src/codegen/**
      - src/checker/**
      - src/parser/**
      - src/lexer/**
      - src/ast/**
      - src/resolver/**
      - src/compiler.ts

language-spec:
  - changed-files:
    - any-glob-to-any-file:
      - docs/**
      - std/**
      - examples/**

runtime:
  - changed-files:
    - any-glob-to-any-file:
      - src/codegen/runtime.ts
      - src/codegen/builtins.ts
      - src/registry/**

tests:
  - changed-files:
    - any-glob-to-any-file:
      - tests/**

ci/cd:
  - changed-files:
    - any-glob-to-any-file:
      - .github/**

docs:
  - changed-files:
    - any-glob-to-any-file:
      - "*.md"
      - docs/**

dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - package.json
      - package-lock.json
